language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=hdbscan
  matrix:
    - DISTRIB="conda"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas networkx scikit-learn pytest pytest-cov codecov coverage cython 
  - conda activate testenv
  - python -c "import numpy; print('numpy %s' % numpy.__version__)"
  - python -c "import scipy; print('scipy %s' % scipy.__version__)"
  - python setup.py develop

script: 
  - conda activate testenv
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
